version: '3'
services:
    app:
        build:
            context: .
            dockerfile: ./src/docker/Dockerfile
        container_name: apex
        restart: unless-stopped
        entrypoint:
            - "/bin/bash"
            - "./src/docker/entrypoint.sh"
        volumes:
            - ./:/var/www/html
            - ./src/docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        networks:
            - network
        depends_on:
            - pgsql
            - nginx
    nginx:
        image: nginx:latest
        container_name: apex_nginx
        restart: unless-stopped
        volumes:
            - ./public:/var/www/html/public
            - ./src/docker/nginx.conf:/etc/nginx/conf.d/default.conf
        environment:
            - NGINX_ERROR_LOG=/var/log/nginx/error.log
            - NGINX_ACCESS_LOG=/var/log/nginx/access.log
        ports:
            - "8080:80"
        networks:
            - network
    pgsql:
        image: postgres:latest
        container_name: apex_postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        ports:
            - "5433:5432"
        networks:
            - network
networks:
    network:
        driver: bridge
